Lesson2_Task1
sagynbek001/EPAM_GO pull request #2
Opened 2021-07-09 19:40 UTC by sagynbek001

1) Print a welcoming message.
2) Print the first 10 Fibonacci numbers by importing a package. 
3) Print a complete ending message using defer keyword.

2021-07-09 20:58 UTC, denislituev reviewed
This commit with first task shouldn't be here in PR with the second task

2021-07-09 21:02 UTC, denislituev requested changes

2021-07-09 21:02 UTC, denislituev commented on lesson_02/fibonacci/fibonacci.go
> +func Print_fib_loop(n int) {
good naming style for functions in go is **camelCase**, not **snake_case**

2021-07-09 21:02 UTC, denislituev commented on lesson_02/fibonacci/fibonacci.go
> +func Print_fib_recursion(n int) {
same here with function naming

2021-07-09 21:02 UTC, denislituev commented on lesson_02/fibonacci/fibonacci.go
> +func fib_nth(nth int) int {
same here with function naming

2021-07-12 08:33 UTC, nikonok approved these changes

2021-07-12 14:19 UTC, denislituev approved these changes

2021-07-12 18:42 UTC, merged