Lesson6_Task123
sagynbek001/EPAM_GO pull request #6
Opened 2021-07-28 22:27 UTC by sagynbek001

1) Print client info in JSON format. All the details must be obtained from the request.  
2) Build TCP connection. If the message sent is an integer, then the server must double it and send it back. If the message is a string, then all the letters must be turned into uppercase.
3) Build an HTTP server that supports GET and POST methods only. Use cookies to save the name and address info about the client.

2021-08-02 21:24 UTC, denislituev requested changes
Good job, fix this minor comments and get approve!

2021-08-02 21:24 UTC, denislituev commented on lesson_06/task06_2/client/main.go
> +		const port = 8081
good practice to define consts on the top level, before main()

2021-08-02 21:24 UTC, denislituev commented on lesson_06/task06_1/main.go
> +	const port = 8080
good practice to define consts on the top level, before main()

2021-08-02 21:24 UTC, denislituev commented on lesson_06/task06_2/client/main.go
> +		fmt.Printf("Sending message: %s; to port: %d\n", message[:len(message)-1], port)
also good approach to define string constants (for ex. some log literals or error messages) 
I recommend to move such strings into constants

2021-08-02 21:24 UTC, denislituev commented on lesson_06/task06_2/client/main.go
> +		fmt.Printf("Message recieved: %s\n", getMessage[:len(getMessage)-1])
same here

2021-08-02 21:24 UTC, denislituev commented on lesson_06/task06_2/server/main.go
> +	const port = 8081
same with const

2021-08-02 21:24 UTC, denislituev commented on lesson_06/task06_3/main.go
> +	if r.Method == "GET" {
We have special consts in http package - http.MethodGet. It is better to use it to avoid unexpected typos or mistakes

2021-08-02 21:24 UTC, denislituev commented on lesson_06/task06_3/main.go
> +	} else if r.Method == "POST" {
here we can use http.MethodPost

2021-08-02 21:24 UTC, denislituev commented on lesson_06/task06_3/main.go
> +	const port = 8080
the same with const

2021-08-03 19:51 UTC, denislituev approved these changes

2021-08-06 10:08 UTC, nikonok requested changes

2021-08-06 10:08 UTC, nikonok commented on lesson_06/task06_1/main.go
> +			Accept:    r.Header["Accept"],
You forget about about other headers that can be passed.
The HW task did not say that only this headers were needed =)
https://en.wikipedia.org/wiki/List_of_HTTP_header_fields
Example:
`curl "http://127.0.0.1:8081/headers" -H "Max-Forwards: 10" should return:`
```json
{
  "Host": "127.0.0.1:8080",
  "UserAgent": "curl/7.68.0",
  "RequestURI": "/headers",
  "Header": {
    "Accept": [
      "*/*"
    ],
    "Max-Forwards": [
      "10"
    ],
    "User-Agent": [
      "curl/7.68.0"
    ]
  }
}
```

2021-08-06 10:08 UTC, nikonok commented on lesson_06/task06_1/main.go
> +	fmt.Fprintf(w, "%s\n", new_json)
```
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Fri, 06 Aug 2021 10:05:24 GMT
< Content-Length: 228
< Content-Type: text/plain; charset=utf-8
```
If you response with json, you should set the appropriate content type

2021-08-06 10:08 UTC, nikonok commented on lesson_06/task06_3/main.go
> +	if r.Method == http.MethodGet {
Better use `switch` here, because it can be transformed into jump table and will work faster. But you code works too=)

2021-08-11 18:58 UTC, merged